version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prospertech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
